version: "3.7"
services:

    node-js:
#       image: node:20-alpine
#       image: node:18.20.4-alpine3.20
#       image: alpine:3.20.2
        image: node:18-alpine
#       image: node:16-alpine

        container_name: maluf_nodejs
#       restart: always
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        entrypoint: /bin/ash # Override Entrypoint
        network_mode: host # Com esta configuração o CONTAINER terá acesso a localhost da máquina, no caso do windows
